name: Create Issue Branch

on:
  issues:
    types:
      - assigned

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.name ${{ secrets.GITHUB_ACTOR }} && git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"

      - name: Create Issue Branch
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .github/issue-branch.yml
          token: ${{ secrets.GITHUB_TOKEN }}